fix: allow for mounting of samba secret

diff --git a/rootfs/etc/cont-init.d/01-setup-ldap-password b/rootfs/etc/cont-init.d/01-setup-ldap-password
--- a/rootfs/etc/cont-init.d/01-setup-ldap-password
+++ b/rootfs/etc/cont-init.d/01-setup-ldap-password
@@ -16,13 +16,18 @@ else
     exit 1
 fi
 
-if [ -z "${SAMBA_LDAP_PASSWORD}" ]; then
-    echo "ERROR: Environment variable SAMBA_LDAP_PASSWORD not set"
-    exit 17
-else
-    smbpasswd -w $SAMBA_LDAP_PASSWORD
-fi
 if [ ! -e $SECRET ]]; then
-    echo "ERROR: $SECRET does not exists"
+    echo "INFO: $SECRET does not exists, creating one"
     exit 15
+
+    if [ -z "${SAMBA_LDAP_PASSWORD}" ]; then
+        echo "ERROR: Environment variable SAMBA_LDAP_PASSWORD not set"
+        exit 17
+    else
+        smbpasswd -w $SAMBA_LDAP_PASSWORD
+    fi
+    if [ ! -e $SECRET ]]; then
+        echo "ERROR: $SECRET does not exists"
+        exit 15
+    fi
 fi
