fix: regular config paths

diff --git a/rootfs/etc/cont-init.d/01-setup-ldap-password b/rootfs/etc/cont-init.d/01-setup-ldap-password
--- a/rootfs/etc/cont-init.d/01-setup-ldap-password
+++ b/rootfs/etc/cont-init.d/01-setup-ldap-password
@@ -9,6 +9,13 @@ else
     exit 1
 fi
 
+if [ -f "${NSLCD_CONFIG}" ]; then
+    echo "INFO: found nslcd config in ${NSLCD_CONFIG}"
+else
+    echo "ERROR: nslcd config not found in ${NSLCD_CONFIG}"
+    exit 1
+fi
+
 if [ -z "${SAMBA_LDAP_PASSWORD}" ]; then
     echo "ERROR: Environment variable SAMBA_LDAP_PASSWORD not set"
     exit 17
